### ISSUE TITLE
7月13日リーダーミーティング 

### ISSUE THREAD

**Issue by OiC-SysDev-Game** [OiC-SysDev-Game/Matchstick#1]
こちらに、報告内容を先に書いておいてください。

そうすると、メンバーの全員が見れますので。

**Comment by nakasuna** [comment]
あああ

**Comment by Daikonnbatake** [comment]
test

**Comment by Daikonnbatake** [comment]
ステージ案まだ未着手です。
各ギミックの大きさ(プレイヤーとの相対的な大きさ)などの仕様が全く分からないので話し合いたいです。

**Comment by e-kidayo** [comment]
自分は前言われたランダムに配置するステージの案を資料はできていませんが、考えています。また、仕様書を作成したので今日中にアップしたいと思います。デザイナーやプログラマーの現状も、もうちょっと詳しく知りたいので少し話し合いたいです。

**Comment by nakasuna** [comment]
デザイン原案を描いてもらっています。
ステージ背景がどのようになるのか話し合いたいです。
また、本日22時からデザイナー会議を開いて方向性やトーンマナーを決めていきたいと考えています。

**Comment by OiC-b9204-Yuto** [comment]
プログラマー
作業担当振り分けと各担当に対してタスクの策定をしました
(タスクの期限は実力把握ができていないので7/14に確認して再度調整する予定です)
※各期限 7/14 ~17:30 (人数)
ステージ担当 - ステージランダム生成の実装 (1)
ギミック担当 - 火をつけれるギミックの実装、それによって動作するギミックの実装 (3)
プレイヤ担当 - 移動処理の実装 (1)

**Comment by Daikonnbatake** [comment]
加賀メモ

描画はマップチップ

ステージは部屋のつながり方をランダマイズ
部屋案作成→デザイン案依頼(リーダー会議で固める)

背景は二重(手前/奥)

ギミック/ステージは自分メインで進める(指示書等含む)
↑
えーきさんの監修後に依頼は出す

**Comment by Daikonnbatake** [comment]
背景のイメージを話し合う(巨木並べる案は結構ありかも)

**Comment by e-kidayo** [comment]
山岡:タスク
ゲームに登場するキャラ、オブジェクトのサイズ決め(指示書制作)
ゲームの根本、方向性をがっちりする
イラストの指示書の制作
山岡:メモ
ギミック
・ロボットの大きさや爆弾の大きさを決めていく
・大きさを絵にして渡していくか
・デザイナーに渡せる絵は渡していく
ステージ
・ステージのランダムの粒度を決めていく
・昔のゼルダみたいにする
・マップの形状は固定する
・スタートとゴールは固定でほとんど同じにする
・ステージ、ギミックは加賀君
・ギミックはランダム
デザイナー
・岩井君にデザイン本書き
・背景のデザインの構成
・スクールの背景は4つそれぞれ朝昼夜、ランダム
・木を手前と奥で決めていく手前は動く
・必要最低限の色にする
・クリア時に何か絵や達成したものを付けていく
・キャラデザの根本が決まっていない
・考え方をガッツリ行ってもらいたい
・イラストの指示書の制作
プログラマー
・作業担当の振り分け
・タスク期限を決めて作って行く
・余裕の有無、タスクの調整
・担当に分けて作って行ってる
・ミーティング水曜、土曜日曜
